name: "Backend Coveralls"

on:
  push:
    branches: [develop, master]

jobs:
  Backend-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to devlop/master branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all package dependencies
        run: yarn

      - name: Generate coverage report
        run: yarn test -- --coverage

      - name: Upload report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
