name: React CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: client

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install all package dependencies
        run: npm install

      - name: Lint the code
        run: npx eslint "src/**" --fix

      # - name: Run Coverage Tests
      #   run:  npm test -- --coverage

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the project
        run: npm run build

      - name: Configure AWS tokens
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy the React App to S3 Bucket
        run: aws s3 cp build s3://twitter-summariser-bucket/ --recursive

