name: Liner

on:
  pull_request:
    branches: [develop]
    
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
       - uses: actions/checkout@v3
       - name: Super-Linter
         uses: github/super-linter@v4.9.2
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
