name: Serverless Deploy

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  Serverless-Deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: yarn

      - name: Build the client
        run: |
          cd client
          yarn
          CI=false yarn run build

      - name: Make the test coverage
        run: |
          cd client
          CI=true yarn test -- --coverage --watchAll=false

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          working-directory: client
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./client/coverage/lcov.info

      - name: Serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
